In [ ]:
#TASK no 1
class Patient:
    def __init__(self, name, age, weight, height):
        self.n = name
        self.a = age
        self.w = weight
        self.h = height
        self.hm = self.h / 100
        self.bmi = self.w / (self.hm ** 2)
    def printDetails(self):
        print('Name: ', self.n)
        print('Age: ', self.a)
        print('weight: ', self.w, 'kg')
        print('height: ', self.h, 'cm')
        print('BMI: ', self.bmi)
p1 = Patient("A", 55, 63.0, 158.0)
p1.printDetails()
print("====================")
p2 = Patient("B", 53, 61.0, 149.0)
p2.printDetails()

Name:  A
Age:  55
weight:  63.0 kg
height:  158.0 cm
BMI:  25.236340330075304
====================
Name:  B
Age:  53
weight:  61.0 kg
height:  149.0 cm
BMI:  27.476239809017613

In [ ]:
#TASK no 2
class Shape:
    def __init__(self, shape, p1, p2):
        self.shape = shape
        self.p1 = p1
        self.p2 = p2
    def area(self):
        if self.shape == 'Triangle':
            self.a = 0.5 * self.p1 * self.p2
            print('Area: ', self.a)
        elif self.shape == 'Square':
            self.a = self.p1 * self.p2
            print('Area: ', self.a)
        elif self.shape == 'Rhombus':
            self.a = 0.5 * self.p1 * self.p2
            print('Area: ', self.a)
        elif self.shape == 'Rectangle':
            self.a = self.p1 * self.p2
            print('Area: ', self.a)
        else:
            print('Area: Shape unknown')
triangle = Shape("Triangle",10,25)
triangle.area()
print("==========================")
square = Shape("Square",10,10)
square.area()
print("==========================")
rhombus = Shape("Rhombus",18,25)
rhombus.area()
print("==========================")
rectangle = Shape("Rectangle",15,30)
rectangle.area()
print("==========================")
trapezium = Shape("Trapezium",15,30)
trapezium.area()

Area:  125.0
==========================
Area:  100
==========================
Area:  225.0
==========================
Area:  450
==========================
Area: Shape unknown

In [ ]:
#TASK no 3
class Calculator:
    def __init__(self):
        print('Calculator is ready!')
    def calculate(self, v1, v2, oparate):
        self.v1 = v1 
        self.v2 = v2
        self.o = oparate
        if self.o == '+':
            val = self.v1 + self.v2
        elif self.o == '-':
            val = self.v1 - self.v2
        elif self.o == '*':
            val = self.v1 * self.v2
        elif self.o == '/':
            val = self.v1 / self.v2
        self.val = val
        return val
    def showCalculation(self):
        print(f'{self.v1} {self.o} {self.v2} = {self.val}')
c1 = Calculator()
print("==================")
val = c1.calculate(10, 20, '+')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 10, '-')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 5, '*')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 16, '/')
print("Returned value:", val)
c1.showCalculation()

Calculator is ready!
==================
Returned value: 30
10 + 20 = 30
==================
Returned value: 20
30 - 10 = 20
==================
Returned value: 100
20 * 5 = 100
==================
Returned value: 6.25
100 / 16 = 6.25

In [ ]:
#TASK no 4
class Programmer:
    def __init__(self, name, language, experience):
        self.n = name
        self.l = language
        self.e = experience
        self.a = None
    def addExp(self, add):
        self.a = add
        self.e = self.e + self.a
        return self.e
    def printDetails(self):
      if self.a == None:
        print('Horray! A new programmer is born')
      else:
        print('Updating experience of', self.n)
      print('Name: ', self.n)
      print('Language: ', self.l)
      print('Experience: ', self.e, 'years')
p1 = Programmer("Ethen Hunt", "Java", 10)
p1.printDetails()
print('--------------------------')
p2 = Programmer("James Bond", "C++", 7)
p2.printDetails()
print('--------------------------')
p3 = Programmer("Jon Snow", "Python", 4)
p3.printDetails()
p3.addExp(5)
p3.printDetails()

Horray! A new programmer is born
Name:  Ethen Hunt
Language:  Java
Experience:  10 years
--------------------------
Horray! A new programmer is born
Name:  James Bond
Language:  C++
Experience:  7 years
--------------------------
Horray! A new programmer is born
Name:  Jon Snow
Language:  Python
Experience:  4 years
Updating experience of Jon Snow
Name:  Jon Snow
Language:  Python
Experience:  9 years

In [ ]:
#TASK no 5
class UberEats:
    def __init__(self, name, phone, address):
        self.n = name
        self.p = phone
        self.a = address
        self.d = {}
        print(self.n, ', welcome to UberEats!')
    def add_items(self, o1, o2, p1, p2):
        self.d = {o1 : p1, o2 : p2}
        self.total = p1 + p2
    def print_order_detail(self):
        print('User details: Name:',self.n,', phone')
        print(self.p, ', Address: ', self.a)
        print('Orders: ', self.d)
        print('Total Paid Amount:', self.total,end = '')
        return ""
order1 = UberEats("Shakib", "01719658xxx", "Mohakhali")
print("=========================")
order1.add_items("Burger", "Coca Cola", 220, 50)
print("=========================")
print(order1.print_order_detail())
print("=========================")
order2 = UberEats ("Siam", "01719659xxx", "Uttara")
print("=========================")
order2.add_items("Pineapple", "Dairy Milk", 80, 70)
print("=========================")
print(order2.print_order_detail())

Shakib , welcome to UberEats!
=========================
=========================
User details: Name: Shakib , phone
01719658xxx , Address:  Mohakhali
Orders:  {'Burger': 220, 'Coca Cola': 50}
Total Paid Amount: 270
=========================
Siam , welcome to UberEats!
=========================
=========================
User details: Name: Siam , phone
01719659xxx , Address:  Uttara
Orders:  {'Pineapple': 80, 'Dairy Milk': 70}
Total Paid Amount: 150

In [ ]:
#Task no 6
class Customer:
    def __init__(self, name):
        self.n = name
    def greet(self, name_1 = None):
        if name_1 == None:
            print('Hello!')
        else:
            print(f"Hello {name_1}!")
    def purchase(self, *args):
        print(f"{self.n}, you purchased {len(args)} item(s)")
        for elem in args:
            print(elem)
customer_1 = Customer("Sam")
customer_1.greet()
customer_1.purchase("chips", "chocolate", "orange juice")
print("-----------------------------")
customer_2 = Customer("David")
customer_2.greet("David")
customer_2.purchase("orange juice")

Hello!
Sam, you purchased 3 item(s)
chips
chocolate
orange juice
-----------------------------
Hello David!
David, you purchased 1 item(s)
orange juice

In [ ]:
#TASK no 7
class Cat:
    def __init__(self, name = None, action = None):
        if name == None and action == None:
            self.n = 'White'
            self.a = 'sitting'
        elif name != None and action == None:
            self.n = name
            self.a = 'sitting'
        else:
            self.n = name
            self.a = action
    def changeColor(self, color = None):
        if color != None:
            self.n = color
    def printCat(self):
        print(f'{self.n} cat is {self.a}')
c1 = Cat()
c2 = Cat("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()

White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Blue cat is sitting
Purple cat is jumping

In [ ]:
 #TASK NO 8
 class Student:
    def __init__(self, name, ID, department = 'CSE'):
        self.n = name
        self.id = ID
        self.d = department
    def dailyEffort(self, time):
        self.t = time
    def printDetails(self):
        print('Name: ', self.n)
        print('ID: ', self.id)
        print('Department: ', self.d)
        print('Daily Effort: ', self.t,'hour(s)')
        if self.t <= 2:
            print('Suggestion: Should give more effort!')
        elif 2 < self.t <= 4:
            print('Suggestion: Keep up the good work!')
        else:
            print('Suggestion: Excellent! Now motivate others.')
harry = Student('Harry Potter', 123)
harry.dailyEffort(3)
harry.printDetails()	
print('========================')
john = Student("John Wick", 456, "BBA")
john.dailyEffort(2)
john.printDetails()
print('========================')
naruto = Student("Naruto Uzumaki", 777, "Ninja")
naruto.dailyEffort(6)
naruto.printDetails()

Name:  Harry Potter
ID:  123
Department:  CSE
Daily Effort:  3 hour(s)
Suggestion: Keep up the good work!
========================
Name:  John Wick
ID:  456
Department:  BBA
Daily Effort:  2 hour(s)
Suggestion: Should give more effort!
========================
Name:  Naruto Uzumaki
ID:  777
Department:  Ninja
Daily Effort:  6 hour(s)
Suggestion: Excellent! Now motivate others.

In [ ]:
#TASK NO 9
class Batsman:
  def  __init__(self, *args):
    if len(args) == 2:
        self.n  = 'New Batsman'
        self.run = args[0]
        self.ball = args[1]
    elif len(args) == 3:
        self.n  = args[0]
        self.run = args[1]
        self.ball = args[2]
  def setName(self, n1):
      self.n = n1
  def printCareerStatistics(self):
      print('Name:', self.n)
      print(f"Runs Scored {self.run}, Balls Faced: {self.ball}")
  def battingStrikeRate(self):
      self.s = self.run / self.ball * 100
      print(self.s)
b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

Name: New Batsman
Runs Scored 6101, Balls Faced: 7380
============================
Name: Liton Das
Runs Scored 678, Balls Faced: 773
----------------------------
87.71021992238033
None
============================
Name: Shakib Al Hasan
Runs Scored 6101, Balls Faced: 7380
----------------------------
82.66937669376694
None

In [ ]:
# TASK no 10
class Author:
    def __init__(self, *args):
        self.book = []
        if len(args) == 0:
            self.name = "Default"
        elif len(args) == 1:
            self.name = args[0]
        else:
            self.name = args[0]
            for elem in range(1, len(args), 1):
                self.book.append(args[elem])

    def addBooks(self, *args):
        for e in args:
            self.book.append(e)

    def changeName(self, name):
        self.name = name

    def printDetails(self):
        print('Author Name: ', self.name)
        print('-----------')
        print('List of Books:')
        for e in self.book:
            print(e)

auth1 = Author('Humayun Ahmed')
auth1.addBooks('Deyal', 'Megher Opor Bari')
auth1.printDetails()
print("===================")
auth2 = Author()
print(auth2.name)
auth2.changeName('Mario Puzo')
auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')
print("===================")
auth2.printDetails()
print("===================")
auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')
auth3.printDetails()

Author Name:  Humayun Ahmed
-----------
List of Books:
Deyal
Megher Opor Bari
===================
Default
===================
Author Name:  Mario Puzo
-----------
List of Books:
The Godfather
Omerta
The Sicilian
===================
Author Name:  Paolo Coelho
-----------
List of Books:
The Alchemist
The Fifth Mountain

In [ ]:
#TASK no 11
class TaxiLagbe:
    def __init__(self, num, place):
        self.num = num
        self.place = place
        self.passenger = []
        self.total = 0

    def addPassenger(self, *args):
        if len(self.passenger) < 4:  
            for elem in args:
                var = elem.split('_')
                self.passenger.append(var[0])

                print(f'Dear {var[0]}! Welcome to TaxiLagbe')
                self.total = self.total + int(var[1])
        else:
            print('Taxi Full! No more passengers can be added.')

    def printDetails(self):
        print('Trip info for Taxi number: ', self.num)
        print('This taxi can cover only ', self.place, "area.")
        print('Total passenger: ', len(self.passenger))
        print("Passenger lists:")
        for i in range(len(self.passenger)):
            if i < len(self.passenger) - 1:
                print(self.passenger[i], end= ',')
            else:
                print(self.passenger[i], "")
        print('Total collected fare: ', self.total, 'Taka')
taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200')
taxi1.addPassenger('Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115')
taxi2.addPassenger('Parker_215')
print('-------------------------------')
taxi2.printDetails()

-------------------------------
Dear Walker! Welcome to TaxiLagbe
Dear Wood! Welcome to TaxiLagbe
Dear Matt! Welcome to TaxiLagbe
Dear Wilson! Welcome to TaxiLagbe
-------------------------------
Trip info for Taxi number:  1010-01
This taxi can cover only  Dhaka area.
Total passenger:  4
Passenger lists:
Walker,Wood,Matt,Wilson
Total collected fare:  505 Taka
-------------------------------
Taxi Full! No more passengers can be added.
-------------------------------
Trip info for Taxi number:  1010-01
This taxi can cover only  Dhaka area.
Total passenger:  4
Passenger lists:
Walker,Wood,Matt,Wilson
Total collected fare:  505 Taka
-------------------------------
Dear Ronald! Welcome to TaxiLagbe
Dear Parker! Welcome to TaxiLagbe
-------------------------------
Trip info for Taxi number:  1010-02
This taxi can cover only  Khulna area.
Total passenger:  2
Passenger lists:
Ronald,Parker
Total collected fare:  330 Taka

In [ ]:
list_1 = ['Walker_100', 'Wood_200']
list_2 = []
x = []
y = []
for i in list_1:
    e = i.split('_')
    print(e)
    x.append(e[0])
    y.append(e[1])
print(x, y)

['Walker', '100']
['Wood', '200']
['Walker', 'Wood'] ['100', '200']

In [ ]:
#TASK no 12
class Account:
    def __init__(self, name = "Defalt Account", balance = 0.0):
        self.name = name
        self.balance = balance

    def details(self):
        print(self.name)
        print(self.balance, end = '')
        return ''
    def withdraw(self, amount):
        if self.balance <= amount:
            print('Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.')
        else:
            self.balance = self.balance - amount
            print('Withdraw successful! New balance is: ', self.balance)
a1 = Account()
print(a1.details())
print("------------------------")
a1.name = "Oliver"
a1.balance = 10000.0
print(a1.details())
print("------------------------")
a2 = Account("Liam")
print(a2.details())
print("------------------------")
a3 = Account("Noah",400)
print(a3.details())
print("------------------------")
a1.withdraw(6930)
print("------------------------")
a2.withdraw(600)
print("------------------------")
a1.withdraw(6929)

Defalt Account
0.0
------------------------
Oliver
10000.0
------------------------
Liam
0.0
------------------------
Noah
400
------------------------
Withdraw successful! New balance is:  3070.0
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.

In [ ]:
#TASK no 13
class StudentDatabase:
    def __init__(self, name, id):
        self.name = name
        self.id = id

    def calculateGPA(self, course, semester):
        self.course = course
        self.semester = semester
        self.grades = {self.semester : self.course}
        self.a = []
        self.sub = []
        self.rel = []
        
        total = 0
        for elem in self.course:
            a = elem.split(': ')
            self.a.append(a)
        for itaretion in self.a:
            self.sub.append(itaretion[0])
            self.rel.append(itaretion[1])
        for i in self.rel:
            total = total + float(i)
        self.gpa = total / len(self.rel)
         
    def printDetails(self):
        print('Name: ', self.name)
        print('ID: ', self.id)
        print(f'Course taken in {self.semester}:') 
        for e in self.sub:
            print(e) 
        print('GPA: ', self.gpa)  
s1 = StudentDatabase('Pietro', '10101222')
s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 'Summer2020')
s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')
print('------------------------------------------------------')
s1.printDetails()
s2 = StudentDatabase('Wanda', '10103332')
s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 'Summer2022')
print('------------------------------------------------------')
print(f'Grades for {s2.name}\n{s2.grades}')
print('------------------------------------------------------')
s2.printDetails()

Grades for Pietro
{'Summer2021': ['CSE250: 3.7', 'CSE330: 4.0']}
------------------------------------------------------
Name:  Pietro
ID:  10101222
Course taken in Summer2021:
CSE250
CSE330
GPA:  3.85
------------------------------------------------------
Grades for Wanda
{'Summer2022': ['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0']}
------------------------------------------------------
Name:  Wanda
ID:  10103332
Course taken in Summer2022:
CSE111
CSE260
ENG101
GPA:  3.8000000000000003

In [ ]:
#TASK 14
class Test3:
    def __init__(self):
        self.sum, self.y = 0, 0
    def methodA(self):
        x, y = 2, 3
        msg = [0]
        msg[0] = 3
        y = self.y + msg[0]
        self.methodB(msg, msg[0])
        x = self.y + msg[0]
        self.sum = x + y + msg[0]
        print(x, y, self.sum)
    def methodB(self, mg2, mg1):
        x = 0
        self.y = self.y + mg2[0]
        x = x + 33 + mg1
        self.sum = self.sum + x + self.y
        mg2[0] = self.y + mg1
        mg1 = mg1 + x + 2
        print(x, self.y, self.sum)
t3 = Test3()
t3.methodA()
t3.methodA()
t3.methodA()
t3.methodA()

36 3 39
9 3 18
36 6 60
15 6 30
36 9 75
21 9 42
36 12 90
27 12 54

In [ ]:
msg = [0]
msg[0] = 3
print(msg, msg[0])

[3] 3